syntax = "proto3";
package products;

service ProductsService {
    rpc GetProductPrice(ProductSkuId) returns (ProductPrice);
    rpc RetrieveProductSkuPrices(ProductSkuIds) returns (ProductSkuPrices);
    rpc GetProductSkuArtifact(RetrieveProductSkuArtifactArgs) returns (ProductSkuArtifact);
    rpc GetLicensePriceFactor(GetLicensePriceFactorArgs) returns (GetLicensePriceFactorResponse);
}

message ProductSkuIds {
    repeated string product_sku_ids = 1;
}

message ProductSkuPrice {
    string product_sku = 1;
    uint64 unit_price = 2;
}

message ProductSkuPrices {
    repeated ProductSkuPrice prices = 1;
}

message ProductSkuId {
    string product_sku_id = 1;
}

message ProductPrice {
    uint64 price = 1;
}

message Empty {}

message RetrieveProductSkuArtifactArgs {
    string product_sku_id = 1;
}

message ProductSkuArtifact {
    string artifact = 1;
}

message GetLicensePriceFactorArgs {
    string license_id = 1;
}

message GetLicensePriceFactorResponse {
    uint64 price_factor = 1;
}
