name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'dev']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  FILES_PATHS: 'services/files/'
  PRODUCTS_SERVICE_PATHS: 'services/products/'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_files_service_changes:
    runs-on: ubuntu-latest
    # needs: [build]
    outputs:
      files_service_should_deploy: ${{ steps.confirm_changes.outputs.FILES_SHOULD_DEPLOY }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: file_changes
        name: Check for Files Service Changes
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"
          files_temp=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          files=$(echo "$files_temp" | tr "\n" " ")
          echo "changed_files=$files" >> "$GITHUB_OUTPUT"

      - id: confirm_changes
        name: Confirm Changes
        shell: bash
        run: |
          echo "Changed files: ${{ steps.file_changes.outputs.changed_files }}"
          echo "If you see here files that you have not modified, please update your branch with changes from main."

          # Check if the modified files include this path
          if echo "${{ steps.file_changes.outputs.changed_files }}" | grep -q "${{ env.FILES_PATHS }}"; then
            # Set the output variable and exit the loop
            echo "triggering_path is ${{ env.FILES_PATHS }}"
            echo "FILES_SHOULD_DEPLOY=true" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"
          else
            echo "FILES_SHOULD_DEPLOY=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
  check_products_service_changes:
    runs-on: ubuntu-latest
    # needs: [build]
    outputs:
      products_service_should_deploy: ${{ steps.confirm_changes.outputs.PRODUCTS_SERVICE_SHOULD_DEPLOY }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: file_changes
        name: Check for Products Service Changes
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"
          files_temp=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          files=$(echo "$files_temp" | tr "\n" " ")
          echo "changed_files=$files" >> "$GITHUB_OUTPUT"

      - id: confirm_changes
        name: Confirm Changes
        shell: bash
        run: |
          echo "Changed files: ${{ steps.file_changes.outputs.changed_files }}"
          echo "If you see here files that you have not modified, please update your branch with changes from main."

          # Check if the modified files include this path
          if echo "${{ steps.file_changes.outputs.changed_files }}" | grep -q "${{ env.PRODUCTS_SERVICE_PATHS }}"; then
            # Set the output variable and exit the loop
            echo "triggering_path is ${{ env.PRODUCTS_SERVICE_PATHS }}"
            echo "PRODUCTS_SERVICE_SHOULD_DEPLOY=true" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"
          else
            echo "PRODUCTS_SERVICE_SHOULD_DEPLOY=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

  build_and_deploy_files:
    runs-on: ubuntu-latest
    needs: [check_files_service_changes]
    if: ${{ needs.check_files_service_changes.outputs.files_service_should_deploy == 'true' }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          docker buildx build --build-arg SERVICE_NAME=files --build-arg PORT=3001 -t elonaire/rt-files:latest --push .

  build_and_deploy_products_service:
    runs-on: ubuntu-latest
    needs: [check_products_service_changes]
    if: ${{ needs.check_products_service_changes.outputs.products_service_should_deploy == 'true' }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          docker buildx build --build-arg SERVICE_NAME=products --build-arg PORT=3004 -t elonaire/rt-products:latest --push .

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: [check_files_service_changes, check_products_service_changes, build_and_deploy_files, build_and_deploy_products_service]
    if: |
      always() &&
      (
        (needs.check_files_service_changes.outputs.files_service_should_deploy == 'true' && needs.build_and_deploy_files.result == 'success' && needs.check_products_service_changes.outputs.products_service_should_deploy == 'false') ||
        (needs.check_products_service_changes.outputs.products_service_should_deploy == 'true' && needs.build_and_deploy_products_service.result == 'success' && needs.check_files_service_changes.outputs.files_service_should_deploy == 'false') ||
        (needs.build_and_deploy_files.result == 'skipped' && needs.build_and_deploy_products_service.result == 'skipped') ||
        needs.build_and_deploy_files.result == 'success' && needs.build_and_deploy_products_service.result == 'success'
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SCP files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # source: "docker-compose.yml,docker-compose.files.yml,docker-compose.shared.yml"
          source: "docker-compose.yml"
          target: ~/

      - name: 'Tar files'
        run: tar -cvf nginx.tar nginx/
      - name: SCP nginx.conf to server
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            source: "nginx.tar"
            target: ~/

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          # key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            tar -xvf nginx.tar
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | CI=true docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            CI=true docker compose --env-file prod.env -f docker-compose.yml --compatibility up -d --force-recreate


  automerge:
    runs-on: ubuntu-latest

    needs: [build_and_deploy_files, build_and_deploy_products_service, deploy_to_server]
    if: |
      always() &&
      (
        (needs.build_and_deploy_files.result == 'success' && needs.build_and_deploy_products_service.result == 'skipped') ||
        (needs.build_and_deploy_products_service.result == 'success' && needs.build_and_deploy_files.result == 'skipped') ||
        (needs.build_and_deploy_files.result == 'skipped' && needs.build_and_deploy_products_service.result == 'skipped') ||
        needs.build_and_deploy_files.result == 'success' && needs.build_and_deploy_products_service.result == 'success'
      )

    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.5'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
